### ISSUE TITLE
Совместимость с cmake

### ISSUE THREAD

**Issue by linotex** [GyverLibs/GyverOLED#1]
После обновления `FastIO.h` при попытке компилировать проект с помощью cmake выбрасывается ошибка
` invalid conversion from ‘volatile uint8_t* {aka volatile unsigned char*}’ to ‘uint8_t* {aka unsigned char*}’` в нескольких строках (24,25,46,47,62,63). Если добавить `volatile` к переменным то все работает (я тестировал на дисплее и Mega 2560). Возможно ли добавить эти изменения в основной код (если надо - создам ПР)? Но боюсь что то сломать потому и спрашиваю )

Спасибо

**Comment by GyverLibs** [comment]
Fast io убран
