### ISSUE TITLE
Невозможно близко подогнать текст в прямоукольнике

### ISSUE THREAD

**Issue by neox-inside** [GyverLibs/GyverOLED#17]
Экран 1306 (128х64), Arduino Nano.
Пример:
```
oled.rect(0, 10, 127, 40, OLED_STROKE); // Draw rect
oled.setScale(2);
oled.setCursorXY(40, 16);
oled.print("10.80");
```

Так всё ок, но там еще есть куча места вверху, поднимаем на -1, `oled.setCursorXY(40, 15);` и число наезжает на прямоугольник. Снизу такое не наблюдается. Может посоветуете что-то?

**Comment by GyverLibs** [comment]
Привет, включить режим наложения текста `oled.textMode(BUF_ADD);`
