### ISSUE TITLE
clear(int x0, int y0, int x1, int y1)

### ISSUE THREAD

**Issue by LastHope0** [GyverLibs/GyverOLED#18]
1) Координаты задаются относительно текущей позиции курсора. О таком следует или предупреждать, или сделать, чтобы отчет был относительно начала координат (левый верхний угол дисплея).
2) нельзя очищать не кратное 8 число пикселей. Тоесть при y = 5, оно очистит от у = 0, до у = 7.

**Comment by GyverLibs** [comment]
1. Координаты задаются аргументами функции, х0 у0 х1 у1. Специально проверил - работает корректно
2. Да, это максимально быстрая очистка области с учётом конструкции дисплея (8-битные столбики). Для очистки точной области можно использовать rect в режиме clear или как он там
