### ISSUE TITLE
Форматирование текн

### ISSUE THREAD

**Issue by ryadavoi** [GyverLibs/GyverOLED#2]
Пользуюсь библиотекой, очень лекгая, понятная, но не хватает расположения текста.

На пример при выводе числа, 4 значного, потом уменьшая его, остаются цифры в конце.  Можно конечно очищать дисплей, но это моргание текста.

**Comment by linotex** [comment]
Привет! Нам известны ширина и высота символа и номер строки где мы выводим текст. Поэтому можно рассчитать позицию вашего числа и очищать только эту область

**Comment by GyverLibs** [comment]
очищай пробелами)

**Comment by ryadavoi** [comment]
Так и сделал )))) проще чем вычислять координаты)) спасибо.
--
Отправлено из Mail.ru для Android среда, 16 июня 2021г., 20:20 +03:00 от Alex  ***@***.*** :
