### ISSUE TITLE
oled.setCursor(x, y) >> oled.Print("Так былобы удобнее", x, y)

### ISSUE THREAD

**Issue by ddmm2005** [GyverLibs/GyverOLED#23]
Думаю из заголовка понятно. Так было бы удобнее, чем каждый раз задавать параметры через setCursor.
туда же можно запихнуть Scale и Invert(True, false)

**Comment by GyverLibs** [comment]
Это невозможно, библиотека использует встроенный интерфейс Print из фреймворка Arduino

**Comment by ddmm2005** [comment]
Понял. Просто когда переписывал код с библиотеки oled_i2c задолбался))). Там так координаты задаются. Но сама либа oled_i2c не зашла. Эта быстрее гораздо

**Comment by GyverLibs** [comment]
Да, тут весь упор был сделан на скорость и возможность работать без буфера
