### ISSUE TITLE
SSH1106 использование встроенного буфера

### ISSUE THREAD

**Issue by ddmm2005** [GyverLibs/GyverOLED#24]
Правильно ли я понял, что если использовать SSH1106 то можно использовать его буфер, тем самым не использовать динамическую память микроконтроллера? Сейчас нет такого дисплея, чтобы проверить. Если так, думаю заказать себе таких дисплеев.

**Comment by GyverLibs** [comment]
Да, можно, но в библиотеке на данный момент не реализовано, и когда будет неизвестно
