### ISSUE TITLE
Некорректный перенос строки

### ISSUE THREAD

**Issue by Kam1k4dze** [GyverLibs/GyverOLED#26]
Экран SSD1306_128x32, OLED_BUFFER.
Код `oled.print("Parametr 1\nParametr 2\nParametr 3\n");`
Выводит на экран это:
```
Parametr 1
           Parametr 2
                      Parametr 3
```

**Comment by GyverLibs** [comment]
в текущей версии перенос строки должен быть по всем правилам - \r\n, в следующем обновлении уберу эту фичу
