### ISSUE TITLE
Can't seem to type "ä, ö, ü"?

### ISSUE THREAD

**Issue by MarcoSchwan** [GyverLibs/GyverOLED#39]
Hello!

Sorry for the silly question. Is there a way to type "a", "ö", "ü"? When doing so, the display instead shows the standard replacement character ("?" in a Rhombus).

Thanks in advance for any help!

**Comment by GyverLibs** [comment]
hello, no it's not. Only ASCII and Russian characters

**Comment by MarcoSchwan** [comment]
Okay, thanks. I'll just use "ae" then..
