### ISSUE TITLE
Symbol degree ° are supported?

### ISSUE THREAD

**Issue by NickyX3** [GyverLibs/GyverOLED#40]
Alex, i try out degree symbol ° (ALT+0176), but out "a" symbol
Алекс, я попробовал вывести символ градуса ° (ALT+0176), но выводится мелкая буква "а"

```
String text = bme.readTemperature() + "°C";
oled.setScale(2);
oled.setCursor(0,0);
oled.print(text);
```

Ожидаемое/Expected 27.74°C
Выводится/Output 27.74aC

**Comment by GyverLibs** [comment]
Only ascii and Cyrillic is supported

**Comment by Olejan** [comment]
> Ожидаемое/Expected 27.74°C Выводится/Output 27.74aC

You can replace any non usable symbol in the _charMap array onto degree code. For instance I do not use this symbol " ` " and use code like this:

```
const uint8_t _charMap[][5] PROGMEM = {
//...
  //{0x00, 0x00, 0x03, 0x04, 0x00}, // ` 0x60 96   <--- comment this
  {0x00, 0x06, 0x09, 0x09, 0x06}, // degree 0x60 96   <--- add this
//...
};
//...

oled.print("Air temp: 27.74`C");
```

_charMap is located in the "src" directory.
