### ISSUE TITLE
error ESP32

### ISSUE THREAD

**Issue by planer-pro** [GyverLibs/GyverOLED#43]
in microWire.cpp

'TWBR' was not declared in this scope
'TWSR' was not declared in this scope
'TWCR' was not declared in this scope
'TWEN' was not declared in this scope
'TWIE' was not declared in this scope

platformio, lolin 32d pro board

**Comment by GyverLibs** [comment]
you cant use microwire on esp32 or other non-AVR platform

**Comment by planer-pro** [comment]
Any solution for run GyverOLED on esp32?

**Comment by GyverLibs** [comment]
there is no problem with esp32
![image](https://github.com/GyverLibs/GyverOLED/assets/84599917/074543be-d6d1-4376-aee9-7302854b45f5)
