### ISSUE TITLE
Проблема с отрисовкой rect с параметром OLED_FILL

### ISSUE THREAD

**Issue by Tlinmo** [GyverLibs/GyverOLED#49]
В общем функция `oled.rect` с параметром `OLED_FILL` рисует прямоугольник с бОльшей стороной x на 1. Ничего бы не сказал, если бы это была именно фича этого метода, но он используется в других методах этого класса и, к сожалению, ломает их (как пример - метод `oled.roundRect` с параметром `OLED_FILL` рисует прямоугольник с кривой правой стороной).
> Пример отрисовки 
![image](https://github.com/user-attachments/assets/5df1cc08-6cc5-4434-abae-c5e500a413f1)

> Код для отрисовки этого примера
```cpp
#include <GyverOLED.h>
GyverOLED<SSD1306_128x64, OLED_BUFFER> oled;
void setup() {
  oled.init();
  oled.clear();
  oled.update();

  oled.rect(0, 0, 6, 6, OLED_FILL);
  oled.rect(0, 8, 6, 14, OLED_STROKE);

  oled.roundRect(0, 16, 6, 22, OLED_FILL);
  oled.roundRect(0, 24, 6, 30, OLED_STROKE);

  oled.update();
}

void loop() {
}
```
> Пояснения на всякий для случая с roundRect
![image](https://github.com/user-attachments/assets/7b1d1e51-19f0-471f-838b-cd16a049068e)

Дополнительно хотелось бы узнать: как без костылей инвертировать часть буфера дисплея? Имею ввиду то, что в других библиотеках есть флаг отрисовки BLACK, WHITE и INVERT, т.е. можно нарисовать тот же самый прямоугольник с параметром INVERT и он инвертирует нарисованную область. Просто в данной библиотеке я такого не нашел. Заранее спасибо

**Comment by BocmenDen** [comment]
Более месяца назад я тоже заметил что квадраты не корректно отрисовываются при написании ЛР ["Игра в змейку"](https://github.com/BocmenDen/SnakeArduino). Результат исправления доступен в симуляторе [wokwi](https://wokwi.com/projects/393708267657200641)

#Проблема 1 - неправильная отрисовка прямоугольника

[Данную](https://github.com/GyverLibs/GyverOLED/blob/1bed45d581a49aa257a29981d55224173e2e5a7a/src/GyverOLED.h#L547) строчку я закоментировал т.к. [ниже](https://github.com/GyverLibs/GyverOLED/blob/1bed45d581a49aa257a29981d55224173e2e5a7a/src/GyverOLED.h#L561) в цикле итерирование идет включительно (<=) и поэтому инкрементирование избыточно. 

#Проблема 2 - похожа на предыдущию только связана с методом update

[Здесь](https://github.com/GyverLibs/GyverOLED/blob/1bed45d581a49aa257a29981d55224173e2e5a7a/src/GyverOLED.h#L809) в цикле граница учтена, а [тут](https://github.com/GyverLibs/GyverOLED/blob/1bed45d581a49aa257a29981d55224173e2e5a7a/src/GyverOLED.h#L808) забыта.
