### ISSUE TITLE
Помощь от сенсея

### ISSUE THREAD

**Issue by VerchVS** [GyverLibs/GyverOLED#54]
Добрый день!
Подскажите пожалуйста, если Вас не затруднит, какие строчки в коде файла библиотеки GyverOLED.h необходимо поменять, чтобы работать с дисплеем SSD1306_96x16. (Для облегчения допустим оставить инициализацию 128х32, но переправить на 96х16)
Благодарю!

**Comment by GyverLibs** [comment]
Библиотека не поддерживает такие размеры. Позже будет новая версия под все оледы

**Comment by VerchVS** [comment]
Спасибо за быстрый ответ!
Будем ждать с нетерпением!)
