### ISSUE TITLE
Поддержка двух дисплеев

### ISSUE THREAD

**Issue by Bestlis** [GyverLibs/GyverOLED#7]
Возможно ли, используя данную библиотеку, подключить два OLED дисплея к одной ардуине?

**Comment by mmorozov-noltic** [comment]
Возможно, вам нужно указать адрес дисплея 

`// для I2C можно передать адрес: GyverOLED oled(0x3C);`

**Comment by Bestlis** [comment]
Да, можно. 
Спасибо за ответ!
Позвольте еще один вопрос: можно ли изменить I2C адрес датчика?
А то получается, что у меня два устройства с одним адресом: 0x3C

**Comment by mmorozov-noltic** [comment]
насколько я знаю на некоторых дисплеях нужно перепаять перемичку

**Comment by mmorozov-noltic** [comment]
Я использую такой https://arduino.ua/prod1264-oled-displei-modyl-sinii

**Comment by Bestlis** [comment]
Да, там есть такая перемычка. 
Программно я так понимаю этого сделать нельзя?

**Comment by mmorozov-noltic** [comment]
насколько я знаю нет (

**Comment by Bestlis** [comment]
Я вас понял.
Спасибо!
