### ISSUE TITLE
Некорректное отображение

### ISSUE THREAD

**Issue by Bestlis** [GyverLibs/GyverOLED#8]
Добрый день!
Имею SSD1306 с возможностью смены I2C адреса с 0x3C на 0x3D. Перепаял перемычку. 
В результате экран отображает данные с разрывами горизонтальных линий пикселей через одну: получается текст в полосках.
Не знаете в чем может быть проблема?

P.S. Такая же ситуация и с вертикальными линиями((

**Comment by Bestlis** [comment]
Здесь можно посмотреть, как это выглядит: https://prnt.sc/26eo8y9

**Comment by GyverLibs** [comment]
привет, что то скриншот не работает

**Comment by Bestlis** [comment]
Попробуйте здесь: https://fbapps.csharpcoding.org/SSD1306.png

**Comment by Bestlis** [comment]
По всей видимости проблемы с самим дисплеем.
