### ISSUE TITLE
Маштабирование  неприятный эффект SSD1306

### ISSUE THREAD

**Issue by schpuntik** [GyverLibs/GyverOLED#9]
Если  маштабировать   цифры  то  появляется  неприятный эффект.  В моём   случае сделал тахометр    всё работало нормально. Решил увеличить размер вывода   и получается  что первый  столбец   пикселей  пропадает   или мигает . Чем  больше маштаб тем больше столбцов пропадает.  Без  маштабирования выводится нормально.  Дисплей SSD1306  128x64  no buffer.

**Comment by GyverLibs** [comment]
Можно минимальный пример, в котором происходит баг? Используется ли буфер? В какие координаты производится вывод?

**Comment by schpuntik** [comment]
https://youtu.be/fGf1oUptcVM  Здесь можно посмотреть

**Comment by linotex** [comment]
Алекс имел ввиду пример кода чтобы у себя попробовать.

**Comment by schpuntik** [comment]
Без проблем могу и код выложить.

**Comment by GyverLibs** [comment]
> Без проблем могу и код выложить. Полностью или только кусок который выводит на дисплей?

Я вроде четко написал что требуется)

**Comment by schpuntik** [comment]
Я в первом посте написал  какой дисплей   и что  буффер не используется.  Вот кусок кода   который  выводится тахометр. Если  этого  мало то могу  и весь код  выложить.
`void datChek() {
  per =  millis() - timer0;
  timer0 = millis();

}

int realSpeed() {
  oled.setScale(3);
  if ((millis() - timer0) < 1000) {
    int nowSpeed;
    nowSpeed = 60000 / per;
    oled.setCursorXY(49, 38);
    delay(100);
    oled.print(nowSpeed);
    oled.print("     ");
    return (nowSpeed);
  } else {
    oled.setCursorXY(49, 38);
    oled.print("СТОП");
    return (0);
  }

}`

**Comment by linotex** [comment]
В идеальном случае нужно выкладывать код который можна Ctrl+C && Ctrl+V и он будеть работать. К примеру у меня нету переменной `per`, соответственно ничего не компилируется(((

**Comment by linotex** [comment]
Также если ви просто скопируете полностю ваш код - ничего не вийдет потому что у вас еще много обвязки (возможно Алекс захочеть собирать это но врятли). Но я думаю данные можна симулировать

**Comment by linotex** [comment]
Минимальний код
```
#include <GyverOLED.h>

static GyverOLED<SSD1306_128x64, OLED_NO_BUFFER> oled;
unsigned long timer0 = 0;
void setup()
{
  oled.init();
      oled.setContrast(255);
      oled.clear();
}

void loop() { 
  if ((millis() - timer0) >= 1000) {
    oled.setScale(3);
    oled.setCursorXY(49, 38);
    timer0 = millis();

    oled.print(timer0);
    oled.print(" ");
  }
}```
`

**Comment by linotex** [comment]
У меня проблема возникает когда `timer0 >= 20000`

**Comment by linotex** [comment]
PS: Єбать Остапа понесло

**Comment by schpuntik** [comment]
https://drive.google.com/file/d/1ixZECcnbqOVe-I4fnnsm5Y7u781JMYKf/view?usp=sharing
Здесь полностью  код.    Я  понял  так что   ему важно  знать  в каком месте выводится это на дисплей.   Я  не  программист  просто  учусь  и не знаю  всех нюансов.  Я просто   взял прошивку   другого  человека и  правлю под мои хотелки.

**Comment by schpuntik** [comment]
Факт  то  что   без маштабирования всё  нормльно   показывает на дисплее. Но для меня  это  слишком мелкий шрифт.  Как начинаю  увиличивать  шрифт  сразу  появляются  артефакты.   Алекс  говорил мне  что без буфера  надо  всегда  кратным 8  пикселям  делать. Так вот я пробывал  двигать  вывод  по дисплею   кратным 8 пикселям  но ничего  не получилось.

**Comment by linotex** [comment]
Но у  вас `setCursor` не кратный 8. Установите `48, 32` к примеру. У меня пофиксилось

**Comment by linotex** [comment]
Заработало или нет? Я только потом увидел что ви уже пробовали устанавливать кратно 8, но надеялся что пофикситься :D

**Comment by schpuntik** [comment]
По Х 48  я пробывал  а вот по У   не помню, вроде тоже. А вот одновременно  ХУ  наверно нет.  У спустил на 40  Так вроде лутьше смотрится. Спасибо!

**Comment by linotex** [comment]
Кул

**Comment by linotex** [comment]
Если проблема решена - пожалуста закройте ишю). Спасибо
